### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by jreina** [CooRay/Promise-Demo#1]
First, a problem: `mywithoutPromiseFunction` doesn't have an explicit return value, so the value of each of the `val#` variables inside of `withoutFunctions` is undefined.

Second, I think to drive the point home you should show an example of callback hell. Get a callback nested like five levels deep with a fake callback-based API, then show the same API converted to Promise-based.

Third, this is a solid example of how simple it is to run a development server with Node. Good job man! 👍

**Comment by CooRay** [comment]
Returning undefined was intentional but I agree, it's a bad example.  I think the callback idea is really good though. I'll implement something like that.  Thanks for the feedback, man.

**Comment by CooRay** [comment]
Closing this. I think this demo needs a complete rewrite.
